# PySNMP SMI module. Autogenerated from smidump -f python SIAE-TREE-MIB
# by libsmi2pysnmp-0.1.3 at Wed Apr  3 15:07:29 2019,
# Python version sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "TimeTicks", "enterprises")

# Objects

siaeMicroelettronicaSpa = ModuleIdentity((1, 3, 6, 1, 4, 1, 3373)).setRevisions(("2014-06-23 00:00","2013-04-16 00:00",))
if mibBuilder.loadTexts: siaeMicroelettronicaSpa.setOrganization("SIAE MICROELETTRONICA spa")
if mibBuilder.loadTexts: siaeMicroelettronicaSpa.setContactInfo("SIAE MICROELETTONICA s.p.a.\nVia Michelangelo Buonarroti, 21\n20093 - Cologno Monzese\nMilano - ITALY\nPhone :  +39-02-27325-1\nE-mail: tbd@siaemic.com")
if mibBuilder.loadTexts: siaeMicroelettronicaSpa.setDescription("SIAE MIB tree root")
siaeMib = MibIdentifier((1, 3, 6, 1, 4, 1, 3373, 1103))

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("SIAE-TREE-MIB", PYSNMP_MODULE_ID=siaeMicroelettronicaSpa)

# Objects
mibBuilder.exportSymbols("SIAE-TREE-MIB", siaeMicroelettronicaSpa=siaeMicroelettronicaSpa, siaeMib=siaeMib)

