#
# PySNMP MIB module SIAE-RAEQ-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file://./sm_raeq.mib
# Produced by pysmi-0.3.2 at Fri Jul 19 08:21:48 2019
# On host 0e190c6811ee platform Linux version 4.9.125-linuxkit by user root
# Using Python version 3.7.3 (default, Apr  3 2019, 05:39:12) 
#
Integer, OctetString, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "Integer", "OctetString", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
SingleValueConstraint, ConstraintsIntersection, ValueRangeConstraint, ConstraintsUnion, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "SingleValueConstraint", "ConstraintsIntersection", "ValueRangeConstraint", "ConstraintsUnion", "ValueSizeConstraint")
AlarmStatus, AlarmSeverityCode = mibBuilder.importSymbols("SIAE-ALARM-MIB", "AlarmStatus", "AlarmSeverityCode")
siaeMib, = mibBuilder.importSymbols("SIAE-TREE-MIB", "siaeMib")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
iso, ObjectIdentity, NotificationType, Counter32, Unsigned32, IpAddress, ModuleIdentity, Counter64, Gauge32, MibIdentifier, Bits, TimeTicks, MibScalar, MibTable, MibTableRow, MibTableColumn, Integer32 = mibBuilder.importSymbols("SNMPv2-SMI", "iso", "ObjectIdentity", "NotificationType", "Counter32", "Unsigned32", "IpAddress", "ModuleIdentity", "Counter64", "Gauge32", "MibIdentifier", "Bits", "TimeTicks", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "Integer32")
TextualConvention, DisplayString, RowStatus = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "DisplayString", "RowStatus")
radioEquip = ModuleIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 15))
radioEquip.setRevisions(('2014-10-07 00:00', '2014-02-04 00:00', '2013-04-16 00:00',))
if mibBuilder.loadTexts: radioEquip.setLastUpdated('201410070000Z')
if mibBuilder.loadTexts: radioEquip.setOrganization('SIAE MICROELETTRONICA spa')
class BitsPerSymbol(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11))
    namedValues = NamedValues(("bpsBPSK", 1), ("bps4QAM", 2), ("bps8PSK", 3), ("bps16QAM", 4), ("bps32QAM", 5), ("bps64QAM", 6), ("bps128QAM", 7), ("bps256QAM", 8), ("bps512QAM", 9), ("bps1024QAM", 10), ("bps2048QAM", 11))

class InterfaceIndexOrZero(TextualConvention, Integer32):
    status = 'current'
    displayHint = 'd'
    subtypeSpec = Integer32.subtypeSpec + ValueRangeConstraint(0, 2147483647)

radioEquipMibVersion = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 1), Integer32().clone(1)).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipMibVersion.setStatus('current')
radioEquipSystem = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))).clone(namedValues=NamedValues(("unequipped", 1), ("radio1p0", 2), ("radio2x1p0NoEthConc", 3), ("radio1p1HeteroFreq", 4), ("radio1p1IsoFreq", 5), ("radio1p1HeteroSpaceDiv", 6), ("radio1p1IsoSpaceDiv", 7), ("radio2x1p0XpicEthConc", 8), ("radio2x1p0XpicNoEthConc", 9), ("radio2x1p0EthConc", 10), ("radio2x1p1XpicMainEthConc", 11), ("radio2x1p1XpicMainNoEthConc", 12), ("radio2x1p1XpicReserveEthConc", 13), ("radio2x1p1XpicReserveNoEthConc", 14))).clone('radio1p0')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipSystem.setStatus('current')
radioEquipFeatureSystemMap = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipFeatureSystemMap.setStatus('current')
radioEquipTable = MibTable((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4), )
if mibBuilder.loadTexts: radioEquipTable.setStatus('current')
radioEquipRecord = MibTableRow((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1), ).setIndexNames((0, "SIAE-RAEQ-MIB", "radioEquipId"))
if mibBuilder.loadTexts: radioEquipRecord.setStatus('current')
radioEquipId = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))).clone(namedValues=NamedValues(("radioEq1A", 1), ("radioEq2A", 2), ("radioEq1B", 3), ("radioEq2B", 4)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipId.setStatus('current')
radioEquipRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 2), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipRowStatus.setStatus('current')
radioEquipIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 3), InterfaceIndexOrZero()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipIfIndex.setStatus('current')
radioEquipLabel = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 4), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 30))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipLabel.setStatus('current')
radioEquipBandwidthAndModulation = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 5), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipBandwidthAndModulation.setStatus('current')
radioEquipTxUpperProfile = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 6), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipTxUpperProfile.setStatus('current')
radioEquipTxLowerProfile = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 7), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipTxLowerProfile.setStatus('current')
radioEquipMaxBandwidthDivisor = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("fullBand", 1), ("halfBand", 2))).clone('fullBand')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipMaxBandwidthDivisor.setStatus('current')
radioEquipAcmEngineEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 9), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipAcmEngineEnable.setStatus('current')
radioEquipAcmPowerMode = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 10), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("constant", 1), ("ramp", 2), ("max", 3))).clone('constant')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipAcmPowerMode.setStatus('current')
radioEquipAcmPowerModeMap = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmPowerModeMap.setStatus('current')
radioEquipReducedCapacityAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 12), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipReducedCapacityAlarm.setStatus('current')
radioEquipAcmRxProfileInUse = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 13), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 34))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmRxProfileInUse.setStatus('current')
radioEquipAcmTxProfileInUse = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 14), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 34))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmTxProfileInUse.setStatus('current')
radioEquipAcmRxProfInUseLabel = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 15), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 30))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmRxProfInUseLabel.setStatus('current')
radioEquipAcmTxProfInUseLabel = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 16), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 30))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmTxProfInUseLabel.setStatus('current')
radioEquipCurrentTxETHCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 17), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipCurrentTxETHCapacity.setStatus('current')
radioEquipCurrentRxETHCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 18), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipCurrentRxETHCapacity.setStatus('current')
radioEquipAcmRxModulationInUse = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 19), BitsPerSymbol()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmRxModulationInUse.setStatus('current')
radioEquipAcmTxModulationInUse = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 20), BitsPerSymbol()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmTxModulationInUse.setStatus('current')
radioEquipAcmRxCodeInUse = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 21), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2))).clone(namedValues=NamedValues(("unknown", 0), ("normal", 1), ("strong", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmRxCodeInUse.setStatus('current')
radioEquipAcmTxCodeInUse = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 22), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2))).clone(namedValues=NamedValues(("unknown", 0), ("normal", 1), ("strong", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmTxCodeInUse.setStatus('current')
radioEquipLinkId = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 23), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 255))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipLinkId.setStatus('current')
radioEquipLinkTelemetryFailAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 24), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipLinkTelemetryFailAlarm.setStatus('current')
radioEquipLinkIdAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 25), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipLinkIdAlarm.setStatus('current')
radioEquipTxPwrThresh = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 26), Integer32().subtype(subtypeSpec=ValueRangeConstraint(3, 15)).clone(3)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipTxPwrThresh.setStatus('current')
radioEquipRxPwrThresh = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 27), Integer32().subtype(subtypeSpec=ValueRangeConstraint(-99, -40)).clone(-70)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipRxPwrThresh.setStatus('current')
radioEquipPermanentTDMCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 28), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 80))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipPermanentTDMCapacity.setStatus('current')
radioEquipE1TypeActionRequest = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 29), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2, 3))).clone(namedValues=NamedValues(("unknown", 0), ("active", 1), ("unframed", 2), ("framed", 3)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipE1TypeActionRequest.setStatus('current')
radioEquipCurrentTxTDMCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 30), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 80))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipCurrentTxTDMCapacity.setStatus('current')
radioEquipCurrentRxTDMCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 31), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 80))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipCurrentRxTDMCapacity.setStatus('current')
radioEquipRxAisAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 32), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipRxAisAlarm.setStatus('current')
radioEquipDemultiplexerFailAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 33), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipDemultiplexerFailAlarm.setStatus('current')
radioEquipMultiplexerFailAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 34), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipMultiplexerFailAlarm.setStatus('current')
radioEquipTxRevertiveSwitch = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 35), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("auto", 1), ("branch1", 2), ("branch2", 3))).clone('auto')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipTxRevertiveSwitch.setStatus('current')
radioEquipRevertiveSwitchWTR = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 36), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 150))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipRevertiveSwitchWTR.setStatus('current')
radioEquipQualityLowRxSw = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 37), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipQualityLowRxSw.setStatus('current')
radioEquipRevertiveAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 38), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipRevertiveAlarm.setStatus('current')
radioEquipTFCControl = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 39), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipTFCControl.setStatus('current')
radioEquipTFCWatchWindow = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 40), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 300)).clone(60)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipTFCWatchWindow.setStatus('current')
radioEquipTFCAlarmThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 41), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 60)).clone(10)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipTFCAlarmThreshold.setStatus('current')
radioEquipTFCAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 42), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipTFCAlarm.setStatus('current')
radioEquipRadioEocLinkAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 43), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipRadioEocLinkAlarm.setStatus('current')
radioEquipRescueModulation = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 44), BitsPerSymbol().clone('bps4QAM')).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipRescueModulation.setStatus('current')
radioEquipSetupMismatchAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 45), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipSetupMismatchAlarm.setStatus('current')
radioEquipRescueSetupAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 46), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipRescueSetupAlarm.setStatus('current')
radioEquipXpicProcedureBlockAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 47), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipXpicProcedureBlockAlarm.setStatus('current')
radioEquipXpicRemTxOffAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 48), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipXpicRemTxOffAlarm.setStatus('current')
radioEquipSynchSetupProtocolEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 49), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipSynchSetupProtocolEnable.setStatus('current')
radioEquipSdhBulkTransport = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 50), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("disable", 1), ("stm1-1", 2), ("stm1-2", 3))).clone('disable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipSdhBulkTransport.setStatus('current')
radioEquipRSSIEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 51), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipRSSIEnable.setStatus('current')
radioEquipProfilesSetSelection = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 4, 1, 52), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("highThroughput", 1), ("highGain", 2)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: radioEquipProfilesSetSelection.setStatus('current')
radioEquipMcmTable = MibTable((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5), )
if mibBuilder.loadTexts: radioEquipMcmTable.setStatus('current')
radioEquipMcmRecord = MibTableRow((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5, 1), ).setIndexNames((0, "SIAE-RAEQ-MIB", "radioEquipId"))
if mibBuilder.loadTexts: radioEquipMcmRecord.setStatus('current')
radioEquipMCMEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 15))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipMCMEnable.setStatus('current')
radioEquipMCMTxVlanId = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 4095))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipMCMTxVlanId.setStatus('current')
radioEquipMCMTxOAMMaintLevel = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 7))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipMCMTxOAMMaintLevel.setStatus('current')
radioEquipMCMFadingHoldOff = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(10, 60)).clone(10)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipMCMFadingHoldOff.setStatus('current')
radioEquipMCMTxPeriod = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("s1", 1), ("s10", 2), ("s60", 3))).clone('s10')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipMCMTxPeriod.setStatus('current')
radioEquipMCMCurrentBWTxType = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 5, 1, 6), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("average", 1), ("min", 2), ("max", 3))).clone('average')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipMCMCurrentBWTxType.setStatus('current')
radioEquipMaintTable = MibTable((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6), )
if mibBuilder.loadTexts: radioEquipMaintTable.setStatus('current')
radioEquipMaintRecord = MibTableRow((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1), ).setIndexNames((0, "SIAE-RAEQ-MIB", "radioEquipId"))
if mibBuilder.loadTexts: radioEquipMaintRecord.setStatus('current')
radioEquipForceLocalTxProfile = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 34))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipForceLocalTxProfile.setStatus('current')
radioEquipForceRemoteTxProfile = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 34))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipForceRemoteTxProfile.setStatus('current')
radioEquipRxForcedSwitch = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("auto", 1), ("branch1", 2), ("branch2", 3))).clone('auto')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipRxForcedSwitch.setStatus('current')
radioEquipTxForcedSwitch = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("auto", 1), ("branch1", 2), ("branch2", 3))).clone('auto')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipTxForcedSwitch.setStatus('current')
radioEquipRevertiveSwitchWTRReset = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("inactive", 0), ("reset", 1)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipRevertiveSwitchWTRReset.setStatus('current')
radioEquipTFCActionRequest = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 6), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("inactive", 0), ("reset", 1)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipTFCActionRequest.setStatus('current')
radioEquipBerStart = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("restart", 1), ("stop", 2))).clone('stop')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipBerStart.setStatus('current')
radioEquipScanningStartCmd = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 6, 1, 9), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipScanningStartCmd.setStatus('current')
radioEquipBerTable = MibTable((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7), )
if mibBuilder.loadTexts: radioEquipBerTable.setStatus('current')
radioEquipBerRecord = MibTableRow((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1), ).setIndexNames((0, "SIAE-RAEQ-MIB", "radioEquipId"))
if mibBuilder.loadTexts: radioEquipBerRecord.setStatus('current')
radioEquipBerErrorCounterH = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1, 1), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipBerErrorCounterH.setStatus('current')
radioEquipBerErrorCounterL = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipBerErrorCounterL.setStatus('current')
radioEquipBerDataCounterH = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1, 3), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipBerDataCounterH.setStatus('current')
radioEquipBerDataCounterL = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1, 4), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipBerDataCounterL.setStatus('current')
radioEquipBerSyncLossAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1, 5), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipBerSyncLossAlarm.setStatus('current')
radioEquipBerSyncLossAlarmCounter = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipBerSyncLossAlarmCounter.setStatus('current')
radioEquipBerElapsedTime = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 7, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipBerElapsedTime.setStatus('current')
radioEquipScanTable = MibTable((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 8), )
if mibBuilder.loadTexts: radioEquipScanTable.setStatus('current')
radioEquipScanRecord = MibTableRow((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 8, 1), ).setIndexNames((0, "SIAE-RAEQ-MIB", "radioEquipId"))
if mibBuilder.loadTexts: radioEquipScanRecord.setStatus('current')
radioEquipScanningFreqMin = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 8, 1, 1), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipScanningFreqMin.setStatus('current')
radioEquipScanningFreqMax = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 8, 1, 2), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipScanningFreqMax.setStatus('current')
radioEquipScanningFreqStep = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 8, 1, 3), Integer32().clone(7000)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipScanningFreqStep.setStatus('current')
radioEquipScanningFreqTime = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 8, 1, 4), Integer32().clone(20)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipScanningFreqTime.setStatus('current')
radioEquipScanningPercentageProgress = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 8, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipScanningPercentageProgress.setStatus('current')
radioEquipAcmTable = MibTable((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9), )
if mibBuilder.loadTexts: radioEquipAcmTable.setStatus('current')
radioEquipAcmRecord = MibTableRow((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1), ).setIndexNames((0, "SIAE-RAEQ-MIB", "radioEquipAcmId"), (0, "SIAE-RAEQ-MIB", "radioEquipAcmProfileId"))
if mibBuilder.loadTexts: radioEquipAcmRecord.setStatus('current')
radioEquipAcmId = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))).clone(namedValues=NamedValues(("radioEq1A", 1), ("radioEq2A", 2), ("radioEq1B", 3), ("radioEq2B", 4)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmId.setStatus('current')
radioEquipAcmProfileId = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 34))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmProfileId.setStatus('current')
radioEquipAcmProfileCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmProfileCapacity.setStatus('current')
radioEquipAcmMaxTDMCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmMaxTDMCapacity.setStatus('current')
radioEquipAcmPowerScaling = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmPowerScaling.setStatus('current')
radioEquipAcmExtraE1TDM = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 21))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipAcmExtraE1TDM.setStatus('current')
radioEquipAcmActiveProfile = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 7), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))).clone(namedValues=NamedValues(("cleared", 1), ("activeRx", 2), ("activeTx", 3), ("activeBoth", 4))).clone('cleared')).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmActiveProfile.setStatus('current')
radioEquipAcmProfileEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmProfileEnable.setStatus('current')
radioEquipAcmDownshiftThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmDownshiftThreshold.setStatus('current')
radioEquipAcmUpshiftThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmUpshiftThreshold.setStatus('current')
radioEquipAcmPermanentTDMCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmPermanentTDMCapacity.setStatus('current')
radioEquipAcmExtraTDMCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmExtraTDMCapacity.setStatus('current')
radioEquipAcmETHCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmETHCapacity.setStatus('current')
radioEquipAcmAtpcRxPowerScaling = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 14), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmAtpcRxPowerScaling.setStatus('current')
radioEquipAcmProfileLabel = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 15), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 31))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipAcmProfileLabel.setStatus('current')
radioEquipAcmProfileModulation = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 16), BitsPerSymbol()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmProfileModulation.setStatus('current')
radioEquipAcmProfileCode = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 17), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("normal", 1), ("strong", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmProfileCode.setStatus('current')
radioEquipAcmPowerRange = MibTableColumn((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 9, 1, 18), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipAcmPowerRange.setStatus('current')
radioEquipLinkTelemetryFailAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 10), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipLinkTelemetryFailAlarmSeverityCode.setStatus('current')
radioEquipLinkIdAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 11), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipLinkIdAlarmSeverityCode.setStatus('current')
radioEquipReducedCapacityAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 12), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipReducedCapacityAlarmSeverityCode.setStatus('current')
radioEquipEowCAIEnable = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 13), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipEowCAIEnable.setStatus('current')
radioEquipEowMasterTerminal = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 14), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipEowMasterTerminal.setStatus('current')
radioEquipEowEnableV11EastSide = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 15), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipEowEnableV11EastSide.setStatus('current')
radioEquipEowEnableV11WestSide = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 16), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipEowEnableV11WestSide.setStatus('current')
radioEquipEowExtPortEnable = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 17), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipEowExtPortEnable.setStatus('current')
radioEquipEowExtOperatorEnable = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 18), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipEowExtOperatorEnable.setStatus('current')
radioEquipAisRxInsertion = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 19), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipAisRxInsertion.setStatus('current')
radioEquipServiceSquelchEnable = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 20), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipServiceSquelchEnable.setStatus('current')
radioEquipCAIAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 21), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipCAIAlarmSeverityCode.setStatus('current')
radioEquipComprFragmMismatchAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 22), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipComprFragmMismatchAlarmSeverityCode.setStatus('current')
radioEquipAisAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 23), AlarmSeverityCode().clone('warningTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipAisAlarmSeverityCode.setStatus('current')
radioEquipDemultiplexerFailAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 24), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipDemultiplexerFailAlarmSeverityCode.setStatus('current')
radioEquipMultiplexerFailAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 25), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipMultiplexerFailAlarmSeverityCode.setStatus('current')
radioEquipRadioEocLinkAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 26), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipRadioEocLinkAlarmSeverityCode.setStatus('current')
radioEquip2MbEocLinkAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 27), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquip2MbEocLinkAlarmSeverityCode.setStatus('current')
radioEquipRevertiveAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 28), AlarmSeverityCode().clone('warningTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipRevertiveAlarmSeverityCode.setStatus('current')
radioEquipTFCAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 29), AlarmSeverityCode().clone('minorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipTFCAlarmSeverityCode.setStatus('current')
radioEquipSetupMismatchAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 30), AlarmSeverityCode().clone('warningTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipSetupMismatchAlarmSeverityCode.setStatus('current')
radioEquipRescueSetupAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 31), AlarmSeverityCode().clone('criticalTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipRescueSetupAlarmSeverityCode.setStatus('current')
radioEquipOnePlusOnePreferential = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 32), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("disable", 1), ("main", 2), ("reserve", 3))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOnePreferential.setStatus('current')
radioEquipOnePlusOneStatusSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 33), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("trapDisable", 1), ("trapEnable", 2))).clone('trapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneStatusSeverityCode.setStatus('current')
radioEquipOnePlusOneMismatchAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 34), AlarmSeverityCode().clone('warningTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneMismatchAlarmSeverityCode.setStatus('current')
radioEquipOnePlusOneTwinFailAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 35), AlarmSeverityCode().clone('warningTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneTwinFailAlarmSeverityCode.setStatus('current')
radioEquipXpicControlProcedure = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 36), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipXpicControlProcedure.setStatus('current')
radioEquipXpicProcedureBlockAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 37), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipXpicProcedureBlockAlarmSeverityCode.setStatus('current')
radioEquipXpicRemTxOffAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 38), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipXpicRemTxOffAlarmSeverityCode.setStatus('current')
radioEquipConcatenationAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 39), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipConcatenationAlarmSeverityCode.setStatus('current')
radioEquipOnePlusOnePreferentialWTR = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 40), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 150)).clone(20)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOnePreferentialWTR.setStatus('current')
radioEquipOnePlusOnePreferentialAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 41), AlarmSeverityCode().clone('warningTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOnePreferentialAlarmSeverityCode.setStatus('current')
radioEquipOnePlusOneTFCControl = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 42), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneTFCControl.setStatus('current')
radioEquipOnePlusOneTFCWatchWindow = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 43), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 300)).clone(60)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneTFCWatchWindow.setStatus('current')
radioEquipOnePlusOneTFCAlarmThreshold = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 44), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 60)).clone(10)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneTFCAlarmThreshold.setStatus('current')
radioEquipOnePlusOneTFCAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 45), AlarmSeverityCode().clone('minorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneTFCAlarmSeverityCode.setStatus('current')
radioEquipFadeMarginMeasure = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 46), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("notRunning", 1), ("running", 2))).clone('notRunning')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipFadeMarginMeasure.setStatus('current')
radioEquipPeripheralLom = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 47), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 4, 6, 8, 16, 24, 30))).clone(namedValues=NamedValues(("disable", 1), ("enableRadio1A", 2), ("enableRadio2A", 4), ("enableRadioA", 6), ("enableRadio1B", 8), ("enableRadio2B", 16), ("enableRadioB", 24), ("enableRadioAll", 30))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipPeripheralLom.setStatus('current')
radioEquipCAIAlarm = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 48), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipCAIAlarm.setStatus('current')
radioEquipComprFragmMismatchAlarm = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 49), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipComprFragmMismatchAlarm.setStatus('current')
radioEquipBaseBandLom = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 50), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 4, 6, 8, 16, 24, 30))).clone(namedValues=NamedValues(("disable", 1), ("enableRadio1A", 2), ("enableRadio2A", 4), ("enableRadioA", 6), ("enableRadio1B", 8), ("enableRadio2B", 16), ("enableRadioB", 24), ("enableRadioAll", 30))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipBaseBandLom.setStatus('current')
radioEquipOnePlusOneLocalStatus = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 51), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7))).clone(namedValues=NamedValues(("active", 1), ("standby", 2), ("activeAlarmed", 3), ("standbyAlarmed", 4), ("forcedActive", 5), ("forcedActiveAlarmed", 6), ("maintenance", 7)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneLocalStatus.setStatus('current')
radioEquipOnePlusOneTwinStatus = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 52), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8))).clone(namedValues=NamedValues(("active", 1), ("standby", 2), ("activeAlarmed", 3), ("standbyAlarmed", 4), ("forcedActive", 5), ("forcedActiveAlarmed", 6), ("maintenance", 7), ("unknown", 8)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneTwinStatus.setStatus('current')
radioEquipOnePlusOneForcedSwitch = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 53), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("disable", 1), ("forced", 2), ("forcedMaintenance", 3))).clone('disable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneForcedSwitch.setStatus('current')
radioEquipOnePlusOneStatus = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 54), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("cleared", 1), ("active", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneStatus.setStatus('current')
radioEquipOnePlusOneMismatchAlarm = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 55), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneMismatchAlarm.setStatus('current')
radioEquipOnePlusOneMismatchMap = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 56), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneMismatchMap.setStatus('current')
radioEquipOnePlusOneTwinFailAlarm = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 57), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneTwinFailAlarm.setStatus('current')
radioEquipOnePlusOneNumberOfSwitch = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 58), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneNumberOfSwitch.setStatus('current')
radioEquipXpicControlResetProcedure = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 59), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("inactive", 0), ("reset", 1))).clone('inactive')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipXpicControlResetProcedure.setStatus('current')
radioEquipConcatenationAlarm = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 60), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipConcatenationAlarm.setStatus('current')
radioEquipOnePlusOnePreferentialWTRReset = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 61), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("inactive", 0), ("reset", 1)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOnePreferentialWTRReset.setStatus('current')
radioEquipOnePlusOnePreferentialAlarm = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 62), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOnePreferentialAlarm.setStatus('current')
radioEquipOnePlusOneTFCActionRequest = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 63), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("inactive", 0), ("reset", 1)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipOnePlusOneTFCActionRequest.setStatus('current')
radioEquipOnePlusOneTFCAlarm = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 64), AlarmStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipOnePlusOneTFCAlarm.setStatus('current')
radioEquipFeatureTDMpresence = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 65), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))).clone(namedValues=NamedValues(("notPresent", 1), ("dynamicOnly", 2), ("permanentOnly", 3), ("bothPresent", 4)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipFeatureTDMpresence.setStatus('current')
radioEquipFeatureMisc = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 66), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipFeatureMisc.setStatus('current')
radioEquipFeatureXpic = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 67), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("notSupported", 1), ("supported", 2), ("enhanced", 3)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: radioEquipFeatureXpic.setStatus('current')
radioEquipBerSyncLossAlarmSeverityCode = MibScalar((1, 3, 6, 1, 4, 1, 3373, 1103, 15, 68), AlarmSeverityCode().clone('majorTrapEnable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: radioEquipBerSyncLossAlarmSeverityCode.setStatus('current')
mibBuilder.exportSymbols("SIAE-RAEQ-MIB", radioEquipRevertiveAlarm=radioEquipRevertiveAlarm, radioEquipScanningFreqStep=radioEquipScanningFreqStep, radioEquipTxUpperProfile=radioEquipTxUpperProfile, radioEquipAcmPermanentTDMCapacity=radioEquipAcmPermanentTDMCapacity, radioEquipSdhBulkTransport=radioEquipSdhBulkTransport, radioEquipOnePlusOnePreferentialAlarmSeverityCode=radioEquipOnePlusOnePreferentialAlarmSeverityCode, radioEquipFadeMarginMeasure=radioEquipFadeMarginMeasure, radioEquipRecord=radioEquipRecord, radioEquipTxPwrThresh=radioEquipTxPwrThresh, radioEquipScanningStartCmd=radioEquipScanningStartCmd, radioEquipEowExtPortEnable=radioEquipEowExtPortEnable, radioEquipOnePlusOneTFCAlarm=radioEquipOnePlusOneTFCAlarm, radioEquipSystem=radioEquipSystem, radioEquipXpicProcedureBlockAlarm=radioEquipXpicProcedureBlockAlarm, radioEquipLinkIdAlarmSeverityCode=radioEquipLinkIdAlarmSeverityCode, radioEquipAcmProfileCapacity=radioEquipAcmProfileCapacity, radioEquipXpicRemTxOffAlarmSeverityCode=radioEquipXpicRemTxOffAlarmSeverityCode, BitsPerSymbol=BitsPerSymbol, radioEquipDemultiplexerFailAlarmSeverityCode=radioEquipDemultiplexerFailAlarmSeverityCode, radioEquipXpicControlProcedure=radioEquipXpicControlProcedure, radioEquipId=radioEquipId, radioEquipAcmProfileId=radioEquipAcmProfileId, radioEquipBerDataCounterL=radioEquipBerDataCounterL, radioEquipRxAisAlarm=radioEquipRxAisAlarm, radioEquipOnePlusOneMismatchAlarm=radioEquipOnePlusOneMismatchAlarm, radioEquipRowStatus=radioEquipRowStatus, radioEquipComprFragmMismatchAlarmSeverityCode=radioEquipComprFragmMismatchAlarmSeverityCode, radioEquipMultiplexerFailAlarm=radioEquipMultiplexerFailAlarm, radioEquipTFCActionRequest=radioEquipTFCActionRequest, radioEquipBerRecord=radioEquipBerRecord, radioEquipAcmTable=radioEquipAcmTable, radioEquipTFCAlarmThreshold=radioEquipTFCAlarmThreshold, radioEquipRxForcedSwitch=radioEquipRxForcedSwitch, radioEquipSetupMismatchAlarmSeverityCode=radioEquipSetupMismatchAlarmSeverityCode, radioEquipOnePlusOnePreferential=radioEquipOnePlusOnePreferential, radioEquipTFCControl=radioEquipTFCControl, radioEquipMCMEnable=radioEquipMCMEnable, radioEquipScanRecord=radioEquipScanRecord, radioEquipCurrentRxETHCapacity=radioEquipCurrentRxETHCapacity, radioEquipBerSyncLossAlarmSeverityCode=radioEquipBerSyncLossAlarmSeverityCode, radioEquipAcmRxCodeInUse=radioEquipAcmRxCodeInUse, radioEquipAcmRxProfileInUse=radioEquipAcmRxProfileInUse, PYSNMP_MODULE_ID=radioEquip, radioEquipEowExtOperatorEnable=radioEquipEowExtOperatorEnable, radioEquipTFCWatchWindow=radioEquipTFCWatchWindow, radioEquipRescueModulation=radioEquipRescueModulation, radioEquipAcmActiveProfile=radioEquipAcmActiveProfile, radioEquipBerSyncLossAlarm=radioEquipBerSyncLossAlarm, radioEquipRevertiveSwitchWTR=radioEquipRevertiveSwitchWTR, radioEquipAcmPowerMode=radioEquipAcmPowerMode, radioEquipTxForcedSwitch=radioEquipTxForcedSwitch, radioEquipCAIAlarmSeverityCode=radioEquipCAIAlarmSeverityCode, radioEquipRadioEocLinkAlarm=radioEquipRadioEocLinkAlarm, radioEquipScanningFreqTime=radioEquipScanningFreqTime, radioEquipOnePlusOnePreferentialWTRReset=radioEquipOnePlusOnePreferentialWTRReset, radioEquipAcmRecord=radioEquipAcmRecord, radioEquipMCMTxVlanId=radioEquipMCMTxVlanId, radioEquipAcmRxModulationInUse=radioEquipAcmRxModulationInUse, radioEquipMCMTxOAMMaintLevel=radioEquipMCMTxOAMMaintLevel, radioEquipAcmPowerScaling=radioEquipAcmPowerScaling, radioEquipMCMTxPeriod=radioEquipMCMTxPeriod, radioEquipAcmTxCodeInUse=radioEquipAcmTxCodeInUse, radioEquipBaseBandLom=radioEquipBaseBandLom, radioEquipFeatureXpic=radioEquipFeatureXpic, radioEquipAcmEngineEnable=radioEquipAcmEngineEnable, radioEquipDemultiplexerFailAlarm=radioEquipDemultiplexerFailAlarm, radioEquipAcmRxProfInUseLabel=radioEquipAcmRxProfInUseLabel, radioEquipOnePlusOneTFCControl=radioEquipOnePlusOneTFCControl, radioEquipCurrentTxETHCapacity=radioEquipCurrentTxETHCapacity, radioEquipAcmTxModulationInUse=radioEquipAcmTxModulationInUse, radioEquipBandwidthAndModulation=radioEquipBandwidthAndModulation, radioEquipAcmMaxTDMCapacity=radioEquipAcmMaxTDMCapacity, radioEquipComprFragmMismatchAlarm=radioEquipComprFragmMismatchAlarm, radioEquipMaintTable=radioEquipMaintTable, radioEquipRevertiveAlarmSeverityCode=radioEquipRevertiveAlarmSeverityCode, radioEquipTxRevertiveSwitch=radioEquipTxRevertiveSwitch, radioEquipLinkTelemetryFailAlarmSeverityCode=radioEquipLinkTelemetryFailAlarmSeverityCode, radioEquipAcmProfileLabel=radioEquipAcmProfileLabel, radioEquipEowMasterTerminal=radioEquipEowMasterTerminal, radioEquipMibVersion=radioEquipMibVersion, radioEquipAcmTxProfileInUse=radioEquipAcmTxProfileInUse, radioEquipLabel=radioEquipLabel, radioEquipAcmPowerRange=radioEquipAcmPowerRange, radioEquipAcmExtraE1TDM=radioEquipAcmExtraE1TDM, radioEquipOnePlusOneTFCActionRequest=radioEquipOnePlusOneTFCActionRequest, radioEquipIfIndex=radioEquipIfIndex, radioEquipOnePlusOneStatusSeverityCode=radioEquipOnePlusOneStatusSeverityCode, radioEquipConcatenationAlarm=radioEquipConcatenationAlarm, radioEquipLinkIdAlarm=radioEquipLinkIdAlarm, radioEquipOnePlusOneForcedSwitch=radioEquipOnePlusOneForcedSwitch, radioEquipMcmRecord=radioEquipMcmRecord, radioEquipPeripheralLom=radioEquipPeripheralLom, radioEquipOnePlusOneNumberOfSwitch=radioEquipOnePlusOneNumberOfSwitch, radioEquipFeatureTDMpresence=radioEquipFeatureTDMpresence, radioEquipOnePlusOneTwinFailAlarm=radioEquipOnePlusOneTwinFailAlarm, radioEquipMCMFadingHoldOff=radioEquipMCMFadingHoldOff, radioEquipE1TypeActionRequest=radioEquipE1TypeActionRequest, radioEquipRadioEocLinkAlarmSeverityCode=radioEquipRadioEocLinkAlarmSeverityCode, radioEquipScanTable=radioEquipScanTable, radioEquipTxLowerProfile=radioEquipTxLowerProfile, radioEquipCurrentTxTDMCapacity=radioEquipCurrentTxTDMCapacity, radioEquipRescueSetupAlarm=radioEquipRescueSetupAlarm, radioEquipConcatenationAlarmSeverityCode=radioEquipConcatenationAlarmSeverityCode, radioEquipCurrentRxTDMCapacity=radioEquipCurrentRxTDMCapacity, radioEquipRescueSetupAlarmSeverityCode=radioEquipRescueSetupAlarmSeverityCode, radioEquipAcmProfileEnable=radioEquipAcmProfileEnable, radioEquipQualityLowRxSw=radioEquipQualityLowRxSw, radioEquipMcmTable=radioEquipMcmTable, radioEquipAcmAtpcRxPowerScaling=radioEquipAcmAtpcRxPowerScaling, radioEquipAcmETHCapacity=radioEquipAcmETHCapacity, radioEquipPermanentTDMCapacity=radioEquipPermanentTDMCapacity, radioEquipTFCAlarm=radioEquipTFCAlarm, radioEquipScanningPercentageProgress=radioEquipScanningPercentageProgress, radioEquipBerStart=radioEquipBerStart, radioEquipBerErrorCounterH=radioEquipBerErrorCounterH, radioEquipOnePlusOneTFCAlarmThreshold=radioEquipOnePlusOneTFCAlarmThreshold, radioEquipLinkTelemetryFailAlarm=radioEquipLinkTelemetryFailAlarm, radioEquipAcmExtraTDMCapacity=radioEquipAcmExtraTDMCapacity, radioEquipSetupMismatchAlarm=radioEquipSetupMismatchAlarm, radioEquipBerSyncLossAlarmCounter=radioEquipBerSyncLossAlarmCounter, radioEquipRSSIEnable=radioEquipRSSIEnable, radioEquipOnePlusOneMismatchAlarmSeverityCode=radioEquipOnePlusOneMismatchAlarmSeverityCode, radioEquipMaxBandwidthDivisor=radioEquipMaxBandwidthDivisor, radioEquipOnePlusOneTFCAlarmSeverityCode=radioEquipOnePlusOneTFCAlarmSeverityCode, radioEquipOnePlusOneLocalStatus=radioEquipOnePlusOneLocalStatus, radioEquipOnePlusOneTwinStatus=radioEquipOnePlusOneTwinStatus, radioEquipForceRemoteTxProfile=radioEquipForceRemoteTxProfile, radioEquipEowEnableV11EastSide=radioEquipEowEnableV11EastSide, radioEquipOnePlusOneStatus=radioEquipOnePlusOneStatus, radioEquipRxPwrThresh=radioEquipRxPwrThresh, radioEquipTFCAlarmSeverityCode=radioEquipTFCAlarmSeverityCode, radioEquipFeatureSystemMap=radioEquipFeatureSystemMap, radioEquipAcmId=radioEquipAcmId, radioEquipLinkId=radioEquipLinkId, radioEquipScanningFreqMax=radioEquipScanningFreqMax, radioEquipOnePlusOneMismatchMap=radioEquipOnePlusOneMismatchMap, radioEquipMultiplexerFailAlarmSeverityCode=radioEquipMultiplexerFailAlarmSeverityCode, radioEquipAcmPowerModeMap=radioEquipAcmPowerModeMap, radioEquipServiceSquelchEnable=radioEquipServiceSquelchEnable, radioEquipProfilesSetSelection=radioEquipProfilesSetSelection, radioEquip2MbEocLinkAlarmSeverityCode=radioEquip2MbEocLinkAlarmSeverityCode, radioEquipBerErrorCounterL=radioEquipBerErrorCounterL, radioEquipAisAlarmSeverityCode=radioEquipAisAlarmSeverityCode, radioEquipRevertiveSwitchWTRReset=radioEquipRevertiveSwitchWTRReset, radioEquipAisRxInsertion=radioEquipAisRxInsertion, radioEquipSynchSetupProtocolEnable=radioEquipSynchSetupProtocolEnable, radioEquipTable=radioEquipTable, radioEquipOnePlusOnePreferentialWTR=radioEquipOnePlusOnePreferentialWTR, InterfaceIndexOrZero=InterfaceIndexOrZero, radioEquipBerDataCounterH=radioEquipBerDataCounterH, radioEquip=radioEquip, radioEquipXpicRemTxOffAlarm=radioEquipXpicRemTxOffAlarm, radioEquipAcmProfileModulation=radioEquipAcmProfileModulation, radioEquipOnePlusOneTFCWatchWindow=radioEquipOnePlusOneTFCWatchWindow, radioEquipMCMCurrentBWTxType=radioEquipMCMCurrentBWTxType, radioEquipEowCAIEnable=radioEquipEowCAIEnable, radioEquipOnePlusOnePreferentialAlarm=radioEquipOnePlusOnePreferentialAlarm, radioEquipEowEnableV11WestSide=radioEquipEowEnableV11WestSide, radioEquipAcmDownshiftThreshold=radioEquipAcmDownshiftThreshold, radioEquipAcmProfileCode=radioEquipAcmProfileCode, radioEquipOnePlusOneTwinFailAlarmSeverityCode=radioEquipOnePlusOneTwinFailAlarmSeverityCode, radioEquipScanningFreqMin=radioEquipScanningFreqMin, radioEquipBerTable=radioEquipBerTable, radioEquipReducedCapacityAlarm=radioEquipReducedCapacityAlarm, radioEquipBerElapsedTime=radioEquipBerElapsedTime, radioEquipReducedCapacityAlarmSeverityCode=radioEquipReducedCapacityAlarmSeverityCode, radioEquipXpicControlResetProcedure=radioEquipXpicControlResetProcedure, radioEquipForceLocalTxProfile=radioEquipForceLocalTxProfile, radioEquipCAIAlarm=radioEquipCAIAlarm, radioEquipXpicProcedureBlockAlarmSeverityCode=radioEquipXpicProcedureBlockAlarmSeverityCode, radioEquipMaintRecord=radioEquipMaintRecord, radioEquipFeatureMisc=radioEquipFeatureMisc, radioEquipAcmUpshiftThreshold=radioEquipAcmUpshiftThreshold, radioEquipAcmTxProfInUseLabel=radioEquipAcmTxProfInUseLabel)
