# PySNMP SMI module. Autogenerated from smidump -f python SIAE-UNITYPE-MIB
# by libsmi2pysnmp-0.1.3 at Mon Apr  8 13:32:51 2019,
# Python version sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( siaeMib, ) = mibBuilder.importSymbols("SIAE-TREE-MIB", "siaeMib")
( Bits, Integer32, ModuleIdentity, MibIdentifier, ObjectIdentity, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "ObjectIdentity", "TimeTicks")

# Objects

unitType = MibIdentifier((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3))
unitTypeUnequipped = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 1))
if mibBuilder.loadTexts: unitTypeUnequipped.setDescription("Unequipped unit")
unitTypeODU = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 5))
if mibBuilder.loadTexts: unitTypeODU.setDescription("Out Door Unit")
unitTypeALFO80HD = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 200))
if mibBuilder.loadTexts: unitTypeALFO80HD.setDescription("ALFO 80GHz HD")
unitTypeALFO80HDelectrical = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 201))
if mibBuilder.loadTexts: unitTypeALFO80HDelectrical.setDescription("ALFO 80GHz HD (electrical ethernet inferface)")
unitTypeALFO80HDelectricalOptical = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 202))
if mibBuilder.loadTexts: unitTypeALFO80HDelectricalOptical.setDescription("ALFO 80GHz HD (electrical and optical ethernet inferface)")
unitTypeALFO80HDoptical = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 203))
if mibBuilder.loadTexts: unitTypeALFO80HDoptical.setDescription("ALFO 80GHz HD (optical ethernet inferface)")
unitTypeAGS20ARI1 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 210))
if mibBuilder.loadTexts: unitTypeAGS20ARI1.setDescription("AGS-20 ARI1")
unitTypeAGS20ARI2 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 211))
if mibBuilder.loadTexts: unitTypeAGS20ARI2.setDescription("AGS-20 ARI-2")
unitTypeAGS20ARI4 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 212))
if mibBuilder.loadTexts: unitTypeAGS20ARI4.setDescription("AGS-20 ARI-4")
unitTypeAGS20DRI4 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 213))
if mibBuilder.loadTexts: unitTypeAGS20DRI4.setDescription("AGS-20 DRI-4")
unitTypeAGS20ARI1TDM2 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 214))
if mibBuilder.loadTexts: unitTypeAGS20ARI1TDM2.setDescription("AGS-20 ARI-1 TDM-2")
unitTypeAGS20ARI1TDM3 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 215))
if mibBuilder.loadTexts: unitTypeAGS20ARI1TDM3.setDescription("AGS-20 ARI-1 TDM-3")
unitTypeAGS20ARI2TDM2 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 216))
if mibBuilder.loadTexts: unitTypeAGS20ARI2TDM2.setDescription("AGS-20 ARI-2 TDM-2")
unitTypeAGS20ARI2TDM3 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 217))
if mibBuilder.loadTexts: unitTypeAGS20ARI2TDM3.setDescription("AGS-20 ARI-2 TDM-3")
unitTypeAGS20ARI4TDM2 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 218))
if mibBuilder.loadTexts: unitTypeAGS20ARI4TDM2.setDescription("AGS-20 ARI-4 TDM-2")
unitTypeAGS20ARI4TDM3 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 219))
if mibBuilder.loadTexts: unitTypeAGS20ARI4TDM3.setDescription("AGS-20 ARI-4 TDM-3")
unitTypeAGS20DRI4TDM2 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 220))
if mibBuilder.loadTexts: unitTypeAGS20DRI4TDM2.setDescription("AGS-20 DRI-4 TDM-2")
unitTypeAGS20DRI4TDM3 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 221))
if mibBuilder.loadTexts: unitTypeAGS20DRI4TDM3.setDescription("AGS-20 DRI-4 TDM-3")
unitTypeAGS20CORE = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 222))
if mibBuilder.loadTexts: unitTypeAGS20CORE.setDescription("AGS-20 CORE")
unitTypeAGS20ARI1DP = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 223))
if mibBuilder.loadTexts: unitTypeAGS20ARI1DP.setDescription("AGS-20 ARI1 Dual Power")
unitTypeAGS20ARI1TDM2DP = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 224))
if mibBuilder.loadTexts: unitTypeAGS20ARI1TDM2DP.setDescription("AGS-20 ARI-1 TDM-2 Dual Power")
unitTypeAGS20ARI1TDM3DP = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 225))
if mibBuilder.loadTexts: unitTypeAGS20ARI1TDM3DP.setDescription("AGS-20 ARI-1 TDM-3 Dual Power")
unitTypeALFOplus2 = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 230))
if mibBuilder.loadTexts: unitTypeALFOplus2.setDescription("ALFOplus2")
unitTypeAGS20ODU = ObjectIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 6, 3, 231))
if mibBuilder.loadTexts: unitTypeAGS20ODU.setDescription("AGS-20 ODU")
unitTypeMib = ModuleIdentity((1, 3, 6, 1, 4, 1, 3373, 1103, 506)).setRevisions(("2015-03-04 00:00","2014-12-01 00:00","2014-03-19 00:00","2014-02-07 00:00","2013-04-16 00:00",))
if mibBuilder.loadTexts: unitTypeMib.setOrganization("SIAE MICROELETTRONICA spa")
if mibBuilder.loadTexts: unitTypeMib.setContactInfo("SIAE MICROELETTONICA s.p.a.\nVia Michelangelo Buonarroti, 21\n20093 - Cologno Monzese\nMilano - ITALY\nPhone :  +39-02-27325-1\nE-mail: help@siaemic.com")
if mibBuilder.loadTexts: unitTypeMib.setDescription("Types of SIAE equipment units.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("SIAE-UNITYPE-MIB", PYSNMP_MODULE_ID=unitTypeMib)

# Objects
mibBuilder.exportSymbols("SIAE-UNITYPE-MIB", unitType=unitType, unitTypeUnequipped=unitTypeUnequipped, unitTypeODU=unitTypeODU, unitTypeALFO80HD=unitTypeALFO80HD, unitTypeALFO80HDelectrical=unitTypeALFO80HDelectrical, unitTypeALFO80HDelectricalOptical=unitTypeALFO80HDelectricalOptical, unitTypeALFO80HDoptical=unitTypeALFO80HDoptical, unitTypeAGS20ARI1=unitTypeAGS20ARI1, unitTypeAGS20ARI2=unitTypeAGS20ARI2, unitTypeAGS20ARI4=unitTypeAGS20ARI4, unitTypeAGS20DRI4=unitTypeAGS20DRI4, unitTypeAGS20ARI1TDM2=unitTypeAGS20ARI1TDM2, unitTypeAGS20ARI1TDM3=unitTypeAGS20ARI1TDM3, unitTypeAGS20ARI2TDM2=unitTypeAGS20ARI2TDM2, unitTypeAGS20ARI2TDM3=unitTypeAGS20ARI2TDM3, unitTypeAGS20ARI4TDM2=unitTypeAGS20ARI4TDM2, unitTypeAGS20ARI4TDM3=unitTypeAGS20ARI4TDM3, unitTypeAGS20DRI4TDM2=unitTypeAGS20DRI4TDM2, unitTypeAGS20DRI4TDM3=unitTypeAGS20DRI4TDM3, unitTypeAGS20CORE=unitTypeAGS20CORE, unitTypeAGS20ARI1DP=unitTypeAGS20ARI1DP, unitTypeAGS20ARI1TDM2DP=unitTypeAGS20ARI1TDM2DP, unitTypeAGS20ARI1TDM3DP=unitTypeAGS20ARI1TDM3DP, unitTypeALFOplus2=unitTypeALFOplus2, unitTypeAGS20ODU=unitTypeAGS20ODU, unitTypeMib=unitTypeMib)

